importing libraries

In [1]:
import tenseal as ts
import pickle
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score

In [2]:

def add_laplace_noise(data, epsilon, reduction_factor):
    sensitivity = 1  # Assuming sensitivity of the data
    original_scale = sensitivity / epsilon
    reduced_scale = original_scale * reduction_factor
    noisy_data = []
    for x in data:
        l=[]
        for element in x:
            l.append(element + np.random.laplace(scale=reduced_scale))
        noisy_data.append(l)
    return noisy_data


key generation

In [3]:
context = ts.context(ts.SCHEME_TYPE.CKKS, poly_modulus_degree = 8192, coeff_mod_bit_sizes = [60, 40, 40, 60])
context.generate_galois_keys()
context.global_scale = 2**40

model

In [4]:
m="heart_model.pkl"
with open(m,'rb') as f:
        model_heart=pickle.load(f)

loading data

In [5]:
X = pd.read_csv('x.csv')
Y = pd.read_csv('y.csv')

In [6]:
X

0         1         2         3         4         5         6  \
0   -0.922713 -1.468418 -0.938515  0.364165 -0.063079 -0.417635 -1.005832   
1    1.283063  0.681005 -0.938515  1.620649 -0.352961 -0.417635 -1.005832   
2   -0.040403  0.681005  0.032031  3.448262  0.709940 -0.417635 -1.005832   
3    0.290464  0.681005  1.002577  1.049520 -1.512490 -0.417635  0.898962   
4    0.290464  0.681005 -0.938515  0.478391 -1.048678 -0.417635  0.898962   
..        ...       ...       ...       ...       ...       ...       ...   
117 -0.040403  0.681005 -0.938515 -0.435415  0.381407 -0.417635 -1.005832   
118  1.283063  0.681005 -0.938515 -0.663867  1.077125 -0.417635 -1.005832   
119  0.511041  0.681005  1.973123  0.135714 -0.816773 -0.417635  0.898962   
120 -1.474158 -1.468418  1.002577 -1.120770  0.420058 -0.417635 -1.005832   
121  0.400752 -1.468418  1.002577 -0.663867  1.811493 -0.417635  0.898962   

            7         8         9        10        11        12  
0    0.102904  1.435481 -0.896862 -0.649113 -0.714429 -0.512922  
1   -0.509323 -0.696631  1.087338  0.976352 -0.714429 -2.148873  
2    1.983316 -0.696631 -0.896862  0.976352  0.265082  1.123029  
3    1.064975 -0.696631  0.483451  0.976352 -0.714429 -0.512922  
4   -0.072018 -0.696631 -0.551783 -0.649113 -0.714429 -2.148873  
..        ...       ...       ...       ...       ...       ...  
117 -1.777508  1.435481  1.001069 -0.649113  0.265082  1.123029  
118  0.059173 -0.696631 -0.551783 -0.649113 -0.714429 -0.512922  
119  0.540209 -0.696631 -0.206705  0.976352  1.244593 -0.512922  
120  0.977514  1.435481 -0.896862  0.976352 -0.714429 -0.512922  
121  0.977514 -0.696631 -0.896862  0.976352 -0.714429 -0.512922  

[122 rows x 13 columns]

In [7]:
Y

target
0         1
1         1
2         0
3         1
4         1
..      ...
117       0
118       1
119       0
120       1
121       1

[122 rows x 1 columns]

In [8]:
x_test=np.array(X)
Y_test=np.array(Y)

In [9]:
x_test

array([[-0.92271345, -1.46841752, -0.93851463, ..., -0.64911323,
        -0.71442887, -0.51292188],
       [ 1.28306308,  0.68100522, -0.93851463, ...,  0.97635214,
        -0.71442887, -2.14887271],
       [-0.04040284,  0.68100522,  0.03203122, ...,  0.97635214,
         0.26508221,  1.12302895],
       ...,
       [ 0.5110413 ,  0.68100522,  1.97312292, ...,  0.97635214,
         1.24459328, -0.51292188],
       [-1.47415758, -1.46841752,  1.00257707, ...,  0.97635214,
        -0.71442887, -0.51292188],
       [ 0.40075247, -1.46841752,  1.00257707, ...,  0.97635214,
        -0.71442887, -0.51292188]])

In [10]:
x_test=add_laplace_noise(x_test, 1, 0.5)
x_test=np.array(x_test)

In [11]:
x_test

array([[-1.6179169 , -0.93279607, -0.8148981 , ..., -0.28857458,
        -0.66751538, -0.38582743],
       [ 1.00207808,  0.49781268,  0.6636022 , ...,  0.60269868,
        -0.75240705, -3.73776721],
       [-0.5320962 , -1.18419244, -0.16554276, ...,  1.38221861,
        -0.52917194,  0.52748381],
       ...,
       [ 0.38859255, -0.09274675,  3.02858071, ...,  0.67196924,
         1.81624328, -1.3086976 ],
       [-1.58472289, -2.11692741,  0.59289328, ...,  0.53850618,
        -1.3215164 , -0.36185705],
       [ 0.96689812, -2.43557028,  0.0132185 , ..., -0.02805204,
        -1.287671  , -0.27837186]])

encrypting data

In [12]:
enc_x_test=[]
for sublist in x_test:
    enc_sub = ts.ckks_vector(context, sublist)
    enc_x_test.append(enc_sub)
enc_x_test = np.array(enc_x_test)


In [13]:
enc_x_test

array([<tenseal.tensors.ckksvector.CKKSVector object at 0x000001E8AFC5FFD0>,
      dtype=object)

In [14]:
Y_test

array([[1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
    

In [15]:
Y_test = Y_test.flatten()
Y_test = Y_test.reshape(-1)


In [16]:
Y_test

array([1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1], dtype=int64)

In [17]:
coef = model_heart.coef_.flatten()
coef = coef.reshape(-1)


In [18]:
coef

array([-0.01585557, -0.56511634,  0.64891111, -0.13193269, -0.05848895,
       -0.0019008 ,  0.25786292,  0.35862251, -0.43554263, -0.64277946,
        0.17592834, -0.56672954, -0.50877719])

encrypting model

In [19]:
enc_coef= ts.ckks_vector(context, coef)

In [20]:
model_heart.intercept_[0]

0.16005757619019084

prediction on encrypted data

In [21]:
prediction=[]

for x in enc_x_test:
    l=model_heart.intercept_[0]
    l+=x.dot(enc_coef)
    prediction.append(l)


In [22]:
prediction

decryption

In [23]:
decrypted_op=[]
for i in range (0,len(prediction)):
    if(prediction[i].decrypt()[0]>0):
        decrypted_op.append(1)
    else:
        decrypted_op.append(0)


In [24]:
decrypted_op

[1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1]

In [25]:
accuracy = accuracy_score(Y_test, decrypted_op)

In [26]:
accuracy

0.819672131147541