In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [4]:
heart_data = pd.read_csv('heart_disease_data.csv')

In [5]:
# print first 5 rows of the dataset
heart_data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [6]:
# Number of rows and cols in dataset
heart_data.shape

(303, 14)

In [7]:
#check for some missing values in dataset
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [8]:
# statistical measures of dataset
heart_data.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [9]:
heart_data['target'].value_counts()

1    165
0    138
Name: target, dtype: int64

Split the other parameters and target

In [10]:
X = heart_data.drop(columns='target', axis=1)
Y = heart_data['target']

In [11]:
print(X)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0    

In [12]:
print(Y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64


Data Standardization

In [13]:
scaler = StandardScaler()

In [14]:
scaler.fit(X)

StandardScaler()

In [15]:
standardized_data = scaler.transform(X)

In [16]:
X = standardized_data
Y = heart_data['target']

In [17]:
print(X)

[[ 0.9521966   0.68100522  1.97312292 ... -2.27457861 -0.71442887
  -2.14887271]
 [-1.91531289  0.68100522  1.00257707 ... -2.27457861 -0.71442887
  -0.51292188]
 [-1.47415758 -1.46841752  0.03203122 ...  0.97635214 -0.71442887
  -0.51292188]
 ...
 [ 1.50364073  0.68100522 -0.93851463 ... -0.64911323  1.24459328
   1.12302895]
 [ 0.29046364  0.68100522 -0.93851463 ... -0.64911323  0.26508221
   1.12302895]
 [ 0.29046364 -1.46841752  0.03203122 ... -0.64911323  0.26508221
  -0.51292188]]


Split the data and Train and Test


In [18]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.4, stratify=Y, random_state=2)

In [19]:
print(X.shape, X_train.shape, X_test.shape)

(303, 13) (181, 13) (122, 13)


In [20]:
X_test

array([[-0.92271345, -1.46841752, -0.93851463, ..., -0.64911323,
        -0.71442887, -0.51292188],
       [ 1.28306308,  0.68100522, -0.93851463, ...,  0.97635214,
        -0.71442887, -2.14887271],
       [-0.04040284,  0.68100522,  0.03203122, ...,  0.97635214,
         0.26508221,  1.12302895],
       ...,
       [ 0.5110413 ,  0.68100522,  1.97312292, ...,  0.97635214,
         1.24459328, -0.51292188],
       [-1.47415758, -1.46841752,  1.00257707, ...,  0.97635214,
        -0.71442887, -0.51292188],
       [ 0.40075247, -1.46841752,  1.00257707, ...,  0.97635214,
        -0.71442887, -0.51292188]])

In [21]:
Y_test

119    1
150    1
248    0
9      1
5      1
      ..
187    0
51     1
286    0
122    1
16     1
Name: target, Length: 122, dtype: int64

In [22]:
df1 = pd.DataFrame(X_test)
df2 = pd.DataFrame(Y_test)

Training Model


In [24]:
model = svm.SVC(kernel='linear')

In [25]:
model.fit(X_train, Y_train)

SVC(kernel='linear')


Model Evaluation

In [26]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [27]:
print('Accuracy score is : ',training_data_accuracy)

Accuracy score is :  0.856353591160221


In [28]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [29]:
X_test_prediction

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1], dtype=int64)

In [30]:
model.coef_[0]

array([-0.01585557, -0.56511634,  0.64891111, -0.13193269, -0.05848895,
       -0.0019008 ,  0.25786292,  0.35862251, -0.43554263, -0.64277946,
        0.17592834, -0.56672954, -0.50877719])

In [31]:
X_test

array([[-0.92271345, -1.46841752, -0.93851463, ..., -0.64911323,
        -0.71442887, -0.51292188],
       [ 1.28306308,  0.68100522, -0.93851463, ...,  0.97635214,
        -0.71442887, -2.14887271],
       [-0.04040284,  0.68100522,  0.03203122, ...,  0.97635214,
         0.26508221,  1.12302895],
       ...,
       [ 0.5110413 ,  0.68100522,  1.97312292, ...,  0.97635214,
         1.24459328, -0.51292188],
       [-1.47415758, -1.46841752,  1.00257707, ...,  0.97635214,
        -0.71442887, -0.51292188],
       [ 0.40075247, -1.46841752,  1.00257707, ...,  0.97635214,
        -0.71442887, -0.51292188]])

In [32]:
print('Accuracy score is : ',test_data_accuracy)

Accuracy score is :  0.819672131147541


Predictive system

In [33]:
input = (67,0,0,106,223,0,1,142,0,0.3,2,2,2)

# change input to m=numpy array
numpy_input = np.asarray(input)

# reshape array for predicting 1 instance
input_reshaped = numpy_input.reshape(1,-1)

std_data = scaler.transform(input_reshaped)


prediction = model.predict(std_data)

if(prediction[0] == 0):
    print('The person does not have heart disease');
else:
    print('The person has disease');

The person has disease


d:\apps\anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [34]:
import pickle as pi

In [35]:
filename = 'heart_model.pkl'
pi.dump(model, open(filename, 'wb'))

In [36]:
# loading the saved model
loaded_model = pi.load(open('heart_model.pkl', 'rb'))

In [37]:
filename2='heart_scaler.pkl'
pi.dump(scaler,open(filename2,'wb'))

In [38]:
input = (67,0,0,106,223,0,1,142,0,0.3,2,2,2)

# change input to m=numpy array
numpy_input = np.asarray(input)

# reshape array for predicting 1 instance
input_reshaped = numpy_input.reshape(1,-1)

std_data = scaler.fit_transform(input_reshaped)


prediction = loaded_model.predict(std_data)

if(prediction[0] == 0):
    print('The person does not have heart disease')
else:
    print('The person has disease')

The person has disease


In [39]:
df1.to_csv("x.csv", index=False)
df2.to_csv("y.csv", index=False)