libraries

In [115]:
import tenseal as ts
import pickle
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score

key generation

In [117]:
context = ts.context(ts.SCHEME_TYPE.BFV, poly_modulus_degree=8192, plain_modulus=1032193, coeff_mod_bit_sizes=[60, 40, 40, 60])
context.global_scale = 2**40
context.generate_galois_keys()



model

In [ ]:
m="heart_model.pkl"
with open(m,'rb') as f:
        model_heart=pickle.load(f)

loading data

In [ ]:
X = pd.read_csv('x.csv')
Y = pd.read_csv('y.csv')

In [ ]:
X

0         1         2         3         4         5         6  \
0   -0.922713 -1.468418 -0.938515  0.364165 -0.063079 -0.417635 -1.005832   
1    1.283063  0.681005 -0.938515  1.620649 -0.352961 -0.417635 -1.005832   
2   -0.040403  0.681005  0.032031  3.448262  0.709940 -0.417635 -1.005832   
3    0.290464  0.681005  1.002577  1.049520 -1.512490 -0.417635  0.898962   
4    0.290464  0.681005 -0.938515  0.478391 -1.048678 -0.417635  0.898962   
..        ...       ...       ...       ...       ...       ...       ...   
117 -0.040403  0.681005 -0.938515 -0.435415  0.381407 -0.417635 -1.005832   
118  1.283063  0.681005 -0.938515 -0.663867  1.077125 -0.417635 -1.005832   
119  0.511041  0.681005  1.973123  0.135714 -0.816773 -0.417635  0.898962   
120 -1.474158 -1.468418  1.002577 -1.120770  0.420058 -0.417635 -1.005832   
121  0.400752 -1.468418  1.002577 -0.663867  1.811493 -0.417635  0.898962   

            7         8         9        10        11        12  
0    0.102904  1.435481 -0.896862 -0.649113 -0.714429 -0.512922  
1   -0.509323 -0.696631  1.087338  0.976352 -0.714429 -2.148873  
2    1.983316 -0.696631 -0.896862  0.976352  0.265082  1.123029  
3    1.064975 -0.696631  0.483451  0.976352 -0.714429 -0.512922  
4   -0.072018 -0.696631 -0.551783 -0.649113 -0.714429 -2.148873  
..        ...       ...       ...       ...       ...       ...  
117 -1.777508  1.435481  1.001069 -0.649113  0.265082  1.123029  
118  0.059173 -0.696631 -0.551783 -0.649113 -0.714429 -0.512922  
119  0.540209 -0.696631 -0.206705  0.976352  1.244593 -0.512922  
120  0.977514  1.435481 -0.896862  0.976352 -0.714429 -0.512922  
121  0.977514 -0.696631 -0.896862  0.976352 -0.714429 -0.512922  

[122 rows x 13 columns]

In [ ]:
Y

target
0         1
1         1
2         0
3         1
4         1
..      ...
117       0
118       1
119       0
120       1
121       1

[122 rows x 1 columns]

In [ ]:
x_test=np.array(X)
Y_test=np.array(Y)

In [ ]:
x_test

array([[-0.92271345, -1.46841752, -0.93851463, ..., -0.64911323,
        -0.71442887, -0.51292188],
       [ 1.28306308,  0.68100522, -0.93851463, ...,  0.97635214,
        -0.71442887, -2.14887271],
       [-0.04040284,  0.68100522,  0.03203122, ...,  0.97635214,
         0.26508221,  1.12302895],
       ...,
       [ 0.5110413 ,  0.68100522,  1.97312292, ...,  0.97635214,
         1.24459328, -0.51292188],
       [-1.47415758, -1.46841752,  1.00257707, ...,  0.97635214,
        -0.71442887, -0.51292188],
       [ 0.40075247, -1.46841752,  1.00257707, ...,  0.97635214,
        -0.71442887, -0.51292188]])

encryption

In [ ]:
enc_x_test=[]
for sublist in x_test:
    enc_sub = ts.bfv_vector(context, sublist)
    enc_x_test.append(enc_sub)
enc_x_test = np.array(enc_x_test)


In [ ]:
enc_x_test

array([<tenseal.tensors.bfvvector.BFVVector object at 0x0000020073E5BC10>,
      dtype=object)

In [ ]:
Y_test

array([[1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
    

In [ ]:
Y_test = Y_test.flatten()
Y_test = Y_test.reshape(-1)


In [ ]:
Y_test

array([1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1], dtype=int64)

In [ ]:
coef = model_heart.coef_.flatten()
coef = coef.reshape(-1)


In [ ]:
coef

array([-0.01585557, -0.56511634,  0.64891111, -0.13193269, -0.05848895,
       -0.0019008 ,  0.25786292,  0.35862251, -0.43554263, -0.64277946,
        0.17592834, -0.56672954, -0.50877719])

encrypting model coef

In [ ]:
enc_coef= ts.bfv_vector(context, coef)

In [ ]:
enc_int= ts.bfv_vector(context,model_heart.intercept_)

In [ ]:
enc_coef

In [ ]:
model_heart.intercept_

array([0.16005758])

In [ ]:
enc_int

prediction

In [ ]:
prediction=[]

for x in enc_x_test:
    l=x.dot(enc_coef)
    prediction.append(l+enc_int)



In [ ]:
prediction

decryption

In [ ]:
decrypted_op=[]
for i in range (0,len(prediction)):
    if(prediction[i].decrypt()[0]>0):
        decrypted_op.append(1)
    else:
        decrypted_op.append(0)


In [ ]:
decrypted_op

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [ ]:
accuracy = accuracy_score(Y_test, decrypted_op)

In [ ]:
accuracy

0.45901639344262296